### ISSUE TITLE
jmx_exporter jar with crate community edition

### ISSUE THREAD

**Issue by aradesai** [crate/jmx_exporter#43]
Is there any way to integrate this jmx_exporter jar with the crate community edition?

**Comment by mfussenegger** [comment]
I think the jmx_exporter jar could be used as documented to get some of the JVM specific metrics, but the additional JMX properties that CrateDB itself exposes wouldn't be available as they require the enterprise version.

**Comment by mfussenegger** [comment]
Closing this given that with CrateDB 4.5 there is no longer a community/enterprise distinction and there is only a single ASL2 licensed version.
