### ISSUE TITLE
0.6.0 does not work with CrateDB nightly (4.4)

### ISSUE THREAD

**Issue by chaudum** [crate/jmx_exporter#46]
After setting `CRATE_JAVA_OPTS="-javaagent:..."` CrateDB does start up, but the specified port (e.g. 8080) returns an empty response:

```console
$ curl -v http://localhost:8080
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.72.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

Tested with CrateDB `crate-4.4.0-202012140003-15ff41d`.

**Comment by juanpardo** [comment]
I managed to make it work with commit `4453fc1`, which is not merged to master yet.

**Comment by chaudum** [comment]
Works with commit https://github.com/crate/jmx_exporter/commit/15319bf214f29c4656092bda26fc0bfd68cc3370
